name: Backport
on:
  pull_request:
    types:
      - close

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
